//! KISS-Classify `structure_key` **reference vectors** — the machine-readable,
//! codec-generated byte-match set consumers diff against (Classify §6.7, sk4).
//!
//! This module is the single in-tree source for the reference token set published
//! as `conformance/corpus/structure_key_vectors.json`. Every token in that file is
//! **emitted by the reference codec at generation time** — positives are
//! [`StructureKey::to_token`] on a constructed key, declines are [`from_token`] run
//! against a malformed input — so nothing is hand-transcribed into the artifact. A
//! consumer diffing its own independent derivation against the file is comparing
//! against the reference implementation's actual output, not a human copy of it.
//!
//! The artifact exists because three independent implementations hand-transcribing
//! the golden tokens out of `tests/structure_key_golden.rs` is three chances to
//! introduce a difference that is not a real divergence — or worse, one that
//! *cancels* a real one. Generating the set once, from the codec, removes that
//! last-mile transcription entirely (mirrors `dtype_manifest.json`, the §6.1 SSOT).
//!
//! Coverage is bound to the frozen golden test additively, NOT by refactoring it:
//! `tests/structure_key_vectors.rs` `include_str!`s the golden source, scans out its
//! `sk4|` token literals, and asserts this set is a superset of them — so a golden
//! cell can never be silently dropped from the artifact, and no second transcription
//! exists to drift against the first.

use crate::structure_key::*;

/// Schema identity of the emitted artifact (mirrors `kiss-dtype-manifest-v1`).
pub const VECTORS_SCHEMA: &str = "kiss-structure-key-vectors-v1";
/// The merged spec/codec commit these vectors are generated from — falsifiable
/// provenance (§6.7 Appendix A at sk4, #131 `SCHEMA_VERSION` 3→4). An artifact that
/// names its source tree is checkable against that tree; one that does not is a
/// claim about an unspecified state.
pub const SOURCE_COMMIT: &str = "19c3ad7";

/// The **vocabulary version** each embedded `<namespace>:` token was generated
/// against (§6.8-0004: a namespace's capability-set vocabulary is owned by that
/// namespace's maintainer, not by KISS).
///
/// Why this exists (#200). The artifact pinned `SOURCE_COMMIT` for the KISS spec
/// and recorded NOTHING about the maintainer-owned vocabularies its tokens are
/// spelled in. So a vocabulary could bump and the artifact go silently wrong with
/// no event marking the transition — and it did: `vulkan.md` reached version 4
/// (five fields, rule V-1) while this artifact still published a four-field token,
/// and the four-leg byte-match AGREED on it, because every consumer derived from
/// the same stale artifact rather than from the maintainer's document.
///
/// A match against a value you did not author is only as fresh as the thing you
/// did not author. This table is what makes that freshness checkable instead of
/// assumed; `reference_vectors_state_a_vocabulary_version_for_every_namespace`
/// ties each entry to the `**Vocabulary version:** N` header of the owning
/// document, so a bump fails CI at the moment it lands.
///
/// Each entry is `(namespace, vocabulary version, capability-set field arity)`.
///
/// The arity is the count of `.`-separated fields the owning document's grammar
/// requires — `cuda` C-1: one field (`sm<N>[<letter>]`); `vulkan` V-1 at v4:
/// exactly five, none omissible. It is pinned here so the GENERATOR can reject a
/// malformed token, and tied to the owning document by
/// `reference_vectors_match_the_namespace_documents`.
pub const NAMESPACE_VOCAB_VERSIONS: &[(&str, u32, usize)] = &[("cuda", 1, 1), ("vulkan", 4, 5)];

/// Validate an embedded `<namespace>:<capability-set>` target against the owning
/// document's grammar, at GENERATION time. Panics on any violation.
///
/// A version stamp catches a vocabulary BUMP; it does not catch a token that was
/// malformed the day it was written (#200). Both produce an artifact whose tokens no
/// consumer can derive independently — and the byte-match cannot tell them apart,
/// because every consumer copies the token from here. Arity is the part of the grammar
/// KISS can enforce without re-implementing a maintainer-owned vocabulary; the field
/// VOCABULARIES stay the maintainer's.
pub fn validate_target_token(target: &str) {
    let (ns, cap) = match target.split_once(':') {
        Some(p) => p,
        None => panic!("structure_key_vectors: target `{target}` has no `<namespace>:` prefix"),
    };
    let want = match NAMESPACE_VOCAB_VERSIONS.iter().find(|(n, _, _)| *n == ns) {
        Some((_, _, a)) => *a,
        None => panic!("structure_key_vectors: target `{target}` names namespace `{ns}:` with no recorded vocabulary; add it to NAMESPACE_VOCAB_VERSIONS (#200)"),
    };
    let got = cap.split('.').count();
    assert_eq!(
        got, want,
        "structure_key_vectors: target `{target}` has {got} capability-set field(s); spec/namespaces/{ns}.md requires exactly {want}. The artifact MUST NOT publish a token malformed under the vocabulary that owns it (#200)."
    );
}

/// The vocabulary version for `ns`, or a hard failure.
///
/// Deliberately a panic rather than an `Option`: this runs in the artifact
/// GENERATOR, and the obligation is that the artifact cannot be produced carrying a
/// namespace whose vocabulary version it is unable to state. A `None` that silently
/// emitted nothing would reproduce the exact defect — an artifact making a claim it
/// has no provenance for.
pub fn namespace_vocab_version(ns: &str) -> u32 {
    match NAMESPACE_VOCAB_VERSIONS.iter().find(|(n, _, _)| *n == ns) {
        Some((_, v, _)) => *v,
        None => panic!(
            "structure_key_vectors: a vector names namespace `{ns}:` but no vocabulary version is recorded for it. Add it to NAMESPACE_VOCAB_VERSIONS with the version from spec/namespaces/{ns}.md. The artifact MUST NOT publish a token whose vocabulary provenance it cannot state (#200)."
        ),
    }
}

// ---- construction helpers (same shapes the golden test constructs) -----------

fn op(contig: Contig, mask: u8, vec: VecWidth, div: DivBucket, flipped: bool) -> OperandSubKey {
    OperandSubKey { contig, bcast_mask: mask, vec, div, flipped }
}
fn co4() -> OperandSubKey { op(Contig::Contiguous, 0x00, VecWidth::V4, DivBucket::D16, false) }
fn co8() -> OperandSubKey { op(Contig::Contiguous, 0x00, VecWidth::V8, DivBucket::D16, false) }
fn br1() -> OperandSubKey { op(Contig::Broadcast, 0x01, VecWidth::V1, DivBucket::D16, false) }
fn co1_d8() -> OperandSubKey { op(Contig::Contiguous, 0x00, VecWidth::V1, DivBucket::D8, false) }
fn co1_da() -> OperandSubKey { op(Contig::Contiguous, 0x00, VecWidth::V1, DivBucket::Da, false) }

fn key(
    op_family: &str,
    dtype: &str,
    target: &str,
    work_class: WorkClass,
    rank: u32,
    operands: Vec<OperandSubKey>,
    reduce: Reduce,
    contraction: Option<Contraction>,
) -> StructureKey {
    StructureKey {
        op_family: op_family.to_string(),
        dtype: dtype.to_string(),
        target: target.to_string(),
        index_width: "ix32".to_string(),
        work_class,
        rank,
        operands,
        reduce,
        contraction,
        acc_mp: None,
    }
}

fn key_acc_mp(
    op_family: &str,
    dtype: &str,
    work_class: WorkClass,
    rank: u32,
    operands: Vec<OperandSubKey>,
    reduce: Reduce,
    acc_mp: Option<AccMp>,
) -> StructureKey {
    StructureKey {
        op_family: op_family.to_string(),
        dtype: dtype.to_string(),
        target: "cuda:sm89".to_string(),
        index_width: "ix32".to_string(),
        work_class,
        rank,
        operands,
        reduce,
        contraction: None,
        acc_mp,
    }
}

/// A dense `f32/f32/f32`, bit-stable, non-batched contraction group of the given
/// M/N/K size classes — the common precision-group shape.
fn ctr(m: SizeClass, n: SizeClass, k: SizeClass, batch: Option<SizeClass>, wdt: &str, acc: &str, out: &str, mp: MathPrecision) -> Contraction {
    Contraction {
        m, n, k, k_div: DivBucket::D16, batch,
        wdt: wdt.to_string(), acc: acc.to_string(), out: out.to_string(), mp,
    }
}

/// The namespace half of a `<namespace>:<capability-set>` target token (§6.8-0001) —
/// e.g. `cuda` for `cuda:sm90`, `vulkan` for `vulkan:sg64...`. The axis a consumer
/// scopes capability exclusions on: a namespace it does not implement is an exclusion,
/// not a divergence.
fn target_namespace(target: &str) -> &str {
    target.split(':').next().unwrap_or(target)
}

// ---- the reference vectors ---------------------------------------------------

/// One canonical positive vector: a constructed [`StructureKey`] and the exact token
/// the codec serializes it to. `token` is the Appendix-A golden literal, asserted
/// equal to `key.to_token()` in the vectors test (the spec-tie); the emitted artifact
/// carries `key.to_token()`, so the two are byte-identical by construction.
pub struct PositiveVector {
    pub name: &'static str,
    pub clause: &'static str,
    pub note: &'static str,
    pub key: StructureKey,
    pub token: &'static str,
}

/// The Appendix-A.1 golden token set plus the two codec-canonical `(acc+mp)`
/// deviation examples the golden test exercises as parses-ok fixtures — the positive
/// half of the byte-match surface.
pub fn positive_vectors() -> Vec<PositiveVector> {
    vec![
        PositiveVector {
            name: "elementwise_binary_canonical",
            clause: "KISS-CLASSIFY-6.7-0001",
            note: "elementwise binary, three contiguous v4 operands, no reduce",
            key: key("bin", "f32", "cuda:sm89", WorkClass::Grid, 2, vec![co4(), co4(), co4()], Reduce::None, None),
            token: "sk4|bin|f32|cuda:sm89|ix32|grid|r2|co/00/v4/d16/f;co/00/v4/d16/f;co/00/v4/d16/f|-",
        },
        PositiveVector {
            name: "elementwise_broadcast_operand",
            clause: "KISS-CLASSIFY-6.7-0004",
            note: "middle operand broadcasts on axis 0 (br/01/v1)",
            key: key("bin", "f32", "cuda:sm89", WorkClass::Grid, 2, vec![co4(), br1(), co4()], Reduce::None, None),
            token: "sk4|bin|f32|cuda:sm89|ix32|grid|r2|co/00/v4/d16/f;br/01/v1/d16/f;co/00/v4/d16/f|-",
        },
        PositiveVector {
            name: "unary_f16_v8",
            clause: "KISS-CLASSIFY-6.7-0003",
            note: "unary f16, two v8 operands",
            key: key("une", "f16", "cuda:sm89", WorkClass::Grid, 2, vec![co8(), co8()], Reduce::None, None),
            token: "sk4|une|f16|cuda:sm89|ix32|grid|r2|co/00/v8/d16/f;co/00/v8/d16/f|-",
        },
        PositiveVector {
            name: "reduction_trailing_axis",
            clause: "KISS-CLASSIFY-6.7-0005",
            note: "reduction over the trailing axis serializes rlast",
            key: key("red", "f32", "cuda:sm89", WorkClass::Warp, 2, vec![co1_d8(), co1_da()], Reduce::Trailing, None),
            token: "sk4|red|f32|cuda:sm89|ix32|warp|r2|co/00/v1/d8/f;co/00/v1/da/f|rlast",
        },
        PositiveVector {
            name: "reduction_all_axes",
            clause: "KISS-CLASSIFY-6.7-0005",
            note: "reduction over all axes serializes rall",
            key: key("red", "f32", "cuda:sm89", WorkClass::Warp, 2, vec![co1_d8(), co1_da()], Reduce::All, None),
            token: "sk4|red|f32|cuda:sm89|ix32|warp|r2|co/00/v1/d8/f;co/00/v1/da/f|rall",
        },
        PositiveVector {
            name: "reduction_rank1_all_axes",
            clause: "KISS-CLASSIFY-6.6-0009",
            note: "rank-1 all-axes reduction",
            key: key("red", "f32", "cuda:sm89", WorkClass::Warp, 1, vec![co1_d8(), co1_da()], Reduce::All, None),
            token: "sk4|red|f32|cuda:sm89|ix32|warp|r1|co/00/v1/d8/f;co/00/v1/da/f|rall",
        },
        PositiveVector {
            name: "reduction_subset_mask",
            clause: "KISS-CLASSIFY-6.7-0005",
            note: "rank-4 reduction over a non-trivial subset -> explicit x<hh> keepdim mask",
            key: key("red", "f32", "cuda:sm89", WorkClass::Block, 4, vec![co1_da(), co1_da()], Reduce::Subset(0x0a), None),
            token: "sk4|red|f32|cuda:sm89|ix32|block|r4|co/00/v1/da/f;co/00/v1/da/f|x0a",
        },
        PositiveVector {
            name: "binary_two_operands",
            clause: "KISS-CLASSIFY-6.7-0001",
            note: "binary with two operands (no third)",
            key: key("bin", "f32", "cuda:sm89", WorkClass::Grid, 2, vec![co4(), co4()], Reduce::None, None),
            token: "sk4|bin|f32|cuda:sm89|ix32|grid|r2|co/00/v4/d16/f;co/00/v4/d16/f|-",
        },
        PositiveVector {
            name: "relu_add_generated_r1",
            clause: "KISS-CLASSIFY-6.7-0001",
            note: "the freeze-gate relu_add cell (#60): rank-1 flat grid-stride, three v4 operands",
            key: key("bin", "f32", "cuda:sm89", WorkClass::Grid, 1, vec![co4(), co4(), co4()], Reduce::None, None),
            token: "sk4|bin|f32|cuda:sm89|ix32|grid|r1|co/00/v4/d16/f;co/00/v4/d16/f;co/00/v4/d16/f|-",
        },
        PositiveVector {
            name: "dense_contraction_cuda",
            clause: "KISS-CLASSIFY-6.7-0006",
            note: "dense gem, f32 weight/acc/out, bit-stable (ctll/.../st)",
            key: key("gem", "f32", "cuda:sm89", WorkClass::Grid, 2, vec![co4(), co4(), co4()], Reduce::None, Some(ctr(SizeClass::Tiny, SizeClass::Large, SizeClass::Large, None, "f32", "f32", "f32", MathPrecision::Stable))),
            token: "sk4|gem|f32|cuda:sm89|ix32|grid|r2|co/00/v4/d16/f;co/00/v4/d16/f;co/00/v4/d16/f|-|ctll/d16/f32/f32/f32/st",
        },
        PositiveVector {
            name: "dense_contraction_vulkan_target",
            clause: "KISS-CLASSIFY-6.8",
            note: "same gem cell on a vulkan capability-set target",
            key: key("gem", "f32", "vulkan:sg64.ops-abr.arith-f16.cm-none.cv-none", WorkClass::Grid, 2, vec![co4(), co4(), co4()], Reduce::None, Some(ctr(SizeClass::Tiny, SizeClass::Large, SizeClass::Large, None, "f32", "f32", "f32", MathPrecision::Stable))),
            token: "sk4|gem|f32|vulkan:sg64.ops-abr.arith-f16.cm-none.cv-none|ix32|grid|r2|co/00/v4/d16/f;co/00/v4/d16/f;co/00/v4/d16/f|-|ctll/d16/f32/f32/f32/st",
        },
        PositiveVector {
            name: "gem_batched_cell",
            clause: "KISS-CLASSIFY-6.7-0006",
            note: "batched gem carries the b<class> coordinate (cmll/.../bm/...)",
            key: key("gem", "f32", "cuda:sm90", WorkClass::Grid, 2, vec![co4(), co4(), co4()], Reduce::None, Some(ctr(SizeClass::Medium, SizeClass::Large, SizeClass::Large, Some(SizeClass::Medium), "f32", "f32", "f32", MathPrecision::Stable))),
            token: "sk4|gem|f32|cuda:sm90|ix32|grid|r2|co/00/v4/d16/f;co/00/v4/d16/f;co/00/v4/d16/f|-|cmll/d16/bm/f32/f32/f32/st",
        },
        PositiveVector {
            name: "simt_f32",
            clause: "KISS-CLASSIFY-6.7-0006",
            note: "SIMT f32, bit-stable mp=st (distinct from TF32 by <mp>)",
            key: key("gem", "f32", "cuda:sm90", WorkClass::Grid, 2, vec![co4(), co4(), co4()], Reduce::None, Some(ctr(SizeClass::Tiny, SizeClass::Large, SizeClass::Large, None, "f32", "f32", "f32", MathPrecision::Stable))),
            token: "sk4|gem|f32|cuda:sm90|ix32|grid|r2|co/00/v4/d16/f;co/00/v4/d16/f;co/00/v4/d16/f|-|ctll/d16/f32/f32/f32/st",
        },
        PositiveVector {
            name: "tf32",
            clause: "KISS-CLASSIFY-6.7-0006",
            note: "TF32, reduced-mantissa mp=rm (same shape as simt_f32, distinct token)",
            key: key("gem", "f32", "cuda:sm90", WorkClass::Grid, 2, vec![co4(), co4(), co4()], Reduce::None, Some(ctr(SizeClass::Tiny, SizeClass::Large, SizeClass::Large, None, "f32", "f32", "f32", MathPrecision::ReducedMantissa))),
            token: "sk4|gem|f32|cuda:sm90|ix32|grid|r2|co/00/v4/d16/f;co/00/v4/d16/f;co/00/v4/d16/f|-|ctll/d16/f32/f32/f32/rm",
        },
        PositiveVector {
            name: "mixed_fp8_e4m3_x_e5m2_f32",
            clause: "KISS-CLASSIFY-6.6-0018",
            note: "mixed-precision FP8: e4m3 x e5m2 -> f32, f32 acc",
            key: key("gem", "f8e4m3fn", "cuda:sm90", WorkClass::Grid, 2, vec![co4(), co4(), co4()], Reduce::None, Some(ctr(SizeClass::Tiny, SizeClass::Large, SizeClass::Large, None, "f8e5m2", "f32", "f32", MathPrecision::Stable))),
            token: "sk4|gem|f8e4m3fn|cuda:sm90|ix32|grid|r2|co/00/v4/d16/f;co/00/v4/d16/f;co/00/v4/d16/f|-|ctll/d16/f8e5m2/f32/f32/st",
        },
        PositiveVector {
            name: "mixed_fp8_e4m3_x_e4m3_f16",
            clause: "KISS-CLASSIFY-6.6-0018",
            note: "mixed-precision FP8: e4m3 x e4m3 -> f16, f32 acc (distinct token from the e5m2 cell)",
            key: key("gem", "f8e4m3fn", "cuda:sm90", WorkClass::Grid, 2, vec![co4(), co4(), co4()], Reduce::None, Some(ctr(SizeClass::Tiny, SizeClass::Large, SizeClass::Large, None, "f8e4m3fn", "f32", "f16", MathPrecision::Stable))),
            token: "sk4|gem|f8e4m3fn|cuda:sm90|ix32|grid|r2|co/00/v4/d16/f;co/00/v4/d16/f;co/00/v4/d16/f|-|ctll/d16/f8e4m3fn/f32/f16/st",
        },
        PositiveVector {
            name: "noncontraction_acc_mp_field",
            clause: "KISS-CLASSIFY-6.7-0013",
            note: "non-gem reduction whose accumulator (f32) deviates from compute (f16): |rlast|f32/st",
            key: key_acc_mp("red", "f16", WorkClass::Warp, 2, vec![co1_d8(), co1_da()], Reduce::Trailing, Some(AccMp { acc: "f32".to_string(), mp: MathPrecision::Stable })),
            token: "sk4|red|f16|cuda:sm89|ix32|warp|r2|co/00/v1/d8/f;co/00/v1/da/f|rlast|f32/st",
        },
        PositiveVector {
            name: "noncontraction_scan_mp_only",
            clause: "KISS-CLASSIFY-6.7-0013",
            note: "scan cell, accumulator == compute (f32) but mp deviates (rm): |-|f32/rm",
            key: key_acc_mp("scn", "f32", WorkClass::Warp, 2, vec![co4(), co4()], Reduce::None, Some(AccMp { acc: "f32".to_string(), mp: MathPrecision::ReducedMantissa })),
            token: "sk4|scn|f32|cuda:sm89|ix32|warp|r2|co/00/v4/d16/f;co/00/v4/d16/f|-|f32/rm",
        },
        PositiveVector {
            name: "noncontraction_acc_deviating_f64",
            clause: "KISS-CLASSIFY-6.7-0013",
            note: "reduction with a deviating f64 accumulator, default mp: |rall|f64/st (a parses-ok fixture in the golden)",
            key: key_acc_mp("red", "f32", WorkClass::Warp, 2, vec![co1_d8(), co1_da()], Reduce::All, Some(AccMp { acc: "f64".to_string(), mp: MathPrecision::Stable })),
            token: "sk4|red|f32|cuda:sm89|ix32|warp|r2|co/00/v1/d8/f;co/00/v1/da/f|rall|f64/st",
        },
        PositiveVector {
            name: "noncontraction_reduction_mp_only",
            clause: "KISS-CLASSIFY-6.7-0013",
            note: "reduction, accumulator == compute (f32) with deviating mp: |rall|f32/rm (a parses-ok fixture in the golden)",
            key: key_acc_mp("red", "f32", WorkClass::Warp, 2, vec![co1_d8(), co1_da()], Reduce::All, Some(AccMp { acc: "f32".to_string(), mp: MathPrecision::ReducedMantissa })),
            token: "sk4|red|f32|cuda:sm89|ix32|warp|r2|co/00/v1/d8/f;co/00/v1/da/f|rall|f32/rm",
        },
    ]
}

/// One decline vector: a malformed (or wrong-schema, or reserved) input and the typed
/// [`KeyDecline`] the reference reader answers it with. The emitted artifact records
/// the codec's LIVE `from_token` result; `expected` is cross-checked against it in the
/// vectors test, so the published decline is both codec-emitted and spec-tied.
pub struct DeclineVector {
    pub name: &'static str,
    pub clause: &'static str,
    pub note: &'static str,
    pub token: String,
    pub expected: KeyDecline,
}

const A_GOLDEN: &str = "sk4|bin|f32|cuda:sm89|ix32|grid|r2|co/00/v4/d16/f;co/00/v4/d16/f;co/00/v4/d16/f|-";

/// The A.2 / recognition-surface decline vectors — the negative half of the byte-match
/// surface. Covers the closed-set membership declines (unknown vs reserved dtype and
/// op-family), the §6.7-0015 version signpost-vs-wall split, and the grown precision
/// fields' malformed forms.
pub fn decline_vectors() -> Vec<DeclineVector> {
    vec![
        DeclineVector {
            name: "unknown_dtype",
            clause: "KISS-CLASSIFY-6.1-0001",
            note: "dtype outside the closed 24-token set",
            token: A_GOLDEN.replacen("|f32|", "|f99|", 1),
            expected: KeyDecline::UnknownDtype,
        },
        DeclineVector {
            name: "reserved_dtype",
            clause: "KISS-CLASSIFY-6.1-0001",
            note: "reserved fnuz dtype: recognized on parse, distinct from unknown",
            token: A_GOLDEN.replacen("|f32|", "|f8e4m3fnuz|", 1),
            expected: KeyDecline::ReservedDtype,
        },
        DeclineVector {
            name: "unknown_op_family",
            clause: "KISS-CLASSIFY-6.5-0006",
            note: "op-family outside the closed 24-code set",
            token: A_GOLDEN.replacen("|bin|", "|zzz|", 1),
            expected: KeyDecline::UnknownOpFamily,
        },
        DeclineVector {
            name: "version_signpost_sk9",
            clause: "KISS-CLASSIFY-6.7-0015",
            note: "well-formed canonical OTHER version -> re-derive signpost, not a wall",
            token: A_GOLDEN.replacen("sk4", "sk9", 1),
            expected: KeyDecline::UnsupportedSchemaVersion { got: 9 },
        },
        DeclineVector {
            name: "version_signpost_sk3",
            clause: "KISS-CLASSIFY-6.7-0014",
            note: "this reference build ships no sk3 decoder arm: a persisted sk3 token is the signpost, never a silent cross-vocab decode",
            token: A_GOLDEN.replacen("sk4", "sk3", 1),
            expected: KeyDecline::UnsupportedSchemaVersion { got: 3 },
        },
        DeclineVector {
            name: "version_wall_leading_zero",
            clause: "KISS-CLASSIFY-6.7-0015",
            note: "non-canonical leading-zero sk04 is the malformed wall, not the signpost",
            token: A_GOLDEN.replacen("sk4|", "sk04|", 1),
            expected: KeyDecline::BadVersionPrefix,
        },
        DeclineVector {
            name: "redundant_acc_mp_all_default",
            clause: "KISS-CLASSIFY-6.7-0013",
            note: "the all-default (acc+mp) spelling is a forbidden redundant emission (rule d)",
            token: "sk4|red|f32|cuda:sm89|ix32|warp|r2|co/00/v1/d8/f;co/00/v1/da/f|rall|f32/st".to_string(),
            expected: KeyDecline::RedundantAccMpField,
        },
        DeclineVector {
            name: "acc_mp_bad_precision_code",
            clause: "KISS-CLASSIFY-6.7-0013",
            note: "the (acc+mp) field with an unrecognized math-precision code (zz)",
            token: "sk4|red|f32|cuda:sm89|ix32|warp|r2|co/00/v1/d8/f;co/00/v1/da/f|rall|f64/zz".to_string(),
            expected: KeyDecline::BadAccMpField,
        },
        DeclineVector {
            name: "contraction_reserved_weight_dtype",
            clause: "KISS-CLASSIFY-6.7-0009",
            note: "a reserved fnuz dtype inside the gem precision group declines as reserved",
            token: "sk4|gem|f32|cuda:sm89|ix32|grid|r2|co/00/v4/d16/f;co/00/v4/d16/f;co/00/v4/d16/f|-|ctll/d16/f32/f8e4m3fnuz/f32/st".to_string(),
            expected: KeyDecline::ReservedDtype,
        },
        DeclineVector {
            name: "contraction_bad_precision_code",
            clause: "KISS-CLASSIFY-6.7-0009",
            note: "the gem precision group with an unrecognized math-precision code (zz)",
            token: "sk4|gem|f32|cuda:sm89|ix32|grid|r2|co/00/v4/d16/f;co/00/v4/d16/f;co/00/v4/d16/f|-|ctll/d16/f32/f32/f32/zz".to_string(),
            expected: KeyDecline::BadContractionField,
        },
        // §6.6-0009 / §6.7-0005 (#160): a reduce `x<hh>` whose reduced set has a canonical
        // `-`/`rall`/`rlast` encoding for its rank overloads a sentinel — decline distinctly.
        DeclineVector {
            name: "noncanonical_reduce_all_axes_r2",
            clause: "KISS-CLASSIFY-6.7-0005",
            note: "x03 at rank 2 is the all-axes set — MUST be rall, never a bitmask",
            token: "sk4|red|f32|cuda:sm89|ix32|warp|r2|co/00/v1/d8/f;co/00/v1/da/f|x03".to_string(),
            expected: KeyDecline::NonCanonicalReduceField,
        },
        DeclineVector {
            name: "noncanonical_reduce_trailing_r2",
            clause: "KISS-CLASSIFY-6.7-0005",
            note: "x02 at rank 2 is the lone innermost axis — MUST be rlast, never a bitmask",
            token: "sk4|red|f32|cuda:sm89|ix32|warp|r2|co/00/v1/d8/f;co/00/v1/da/f|x02".to_string(),
            expected: KeyDecline::NonCanonicalReduceField,
        },
        DeclineVector {
            name: "noncanonical_reduce_rank1",
            clause: "KISS-CLASSIFY-6.7-0005",
            note: "x01 at rank 1 is both all-axes and lone-trailing (they coincide) — MUST be rall (§6.6-0009 tie-break)",
            token: "sk4|red|f32|cuda:sm89|ix32|warp|r1|co/00/v1/d8/f;co/00/v1/da/f|x01".to_string(),
            expected: KeyDecline::NonCanonicalReduceField,
        },
        DeclineVector {
            name: "noncanonical_reduce_empty",
            clause: "KISS-CLASSIFY-6.7-0005",
            note: "x00 is the empty reduced set — that is not a reduction, spelled `-`, never a bitmask",
            token: "sk4|red|f32|cuda:sm89|ix32|warp|r2|co/00/v1/d8/f;co/00/v1/da/f|x00".to_string(),
            expected: KeyDecline::NonCanonicalReduceField,
        },
        // §6.7-0009: a bit set for a non-existent axis (index >= rank) is a DIFFERENT producer
        // bug — kept visibly separate so a consumer can see both declines and tell them apart.
        DeclineVector {
            name: "out_of_range_reduce_mask_r2",
            clause: "KISS-CLASSIFY-6.7-0009",
            note: "x04 at rank 2 sets bit 2, an axis that does not exist — out-of-range mask, not a sentinel overload",
            token: "sk4|red|f32|cuda:sm89|ix32|warp|r2|co/00/v1/d8/f;co/00/v1/da/f|x04".to_string(),
            expected: KeyDecline::BadReduceField,
        },
    ]
}

// ---- JSON emission (stdlib-only; the crate shares no code with an impl, §6.5) ---

/// Escape a string for a JSON double-quoted value. All authored strings here are
/// ASCII with no quote/backslash, but this is defensive so a note edit cannot emit
/// malformed JSON.
fn json_str(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    out.push('"');
    for c in s.chars() {
        match c {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            c if (c as u32) < 0x20 => out.push_str(&format!("\\u{:04x}", c as u32)),
            c => out.push(c),
        }
    }
    out.push('"');
    out
}

/// The STABLE published spelling of a [`KeyDecline`] for the artifact — the decline
/// contract, decoupled from Rust's `Debug` (documented as NOT a stable format, so
/// `format!("{e:?}")` would let a field rename or a struct-variant reshape silently
/// re-spell a value three implementations byte-compare against). Returns the decline
/// KIND and an optional structured numeric payload `(key, value)`, so a consumer
/// matches on the kind and reads the payload as a JSON number rather than parsing Rust
/// struct syntax (`"UnsupportedSchemaVersion { got: 3 }"`) out of a string.
///
/// WILDCARD-FREE and compiled on both CI legs (no `#[cfg]`): a new `KeyDecline` variant
/// is a generation-time build failure (E0004) here, not a new spelling that appears in
/// the artifact unannounced. Payload-free variants keep their pre-existing spellings, so
/// this is a hardening of the two payloaded variants, not a wire change for the rest.
fn decline_wire(e: &KeyDecline) -> (&'static str, Option<(&'static str, String)>) {
    match e {
        KeyDecline::WrongFieldCount { got } => ("WrongFieldCount", Some(("got", got.to_string()))),
        KeyDecline::BadVersionPrefix => ("BadVersionPrefix", None),
        KeyDecline::UnsupportedSchemaVersion { got } => ("UnsupportedSchemaVersion", Some(("got", got.to_string()))),
        KeyDecline::BadRank => ("BadRank", None),
        KeyDecline::BadWorkClass => ("BadWorkClass", None),
        KeyDecline::BadOperandSubKey => ("BadOperandSubKey", None),
        KeyDecline::BadReduceField => ("BadReduceField", None),
        KeyDecline::BadContractionField => ("BadContractionField", None),
        KeyDecline::UppercaseOrWidthHex => ("UppercaseOrWidthHex", None),
        KeyDecline::UnknownOpFamily => ("UnknownOpFamily", None),
        KeyDecline::UnknownDtype => ("UnknownDtype", None),
        KeyDecline::ReservedDtype => ("ReservedDtype", None),
        KeyDecline::TokenLengthOutOfBound { len } => ("TokenLengthOutOfBound", Some(("len", len.to_string()))),
        KeyDecline::TooManyOperands { got } => ("TooManyOperands", Some(("got", got.to_string()))),
        KeyDecline::BadTargetGrammar => ("BadTargetGrammar", None),
        KeyDecline::BadTargetCharset => ("BadTargetCharset", None),
        KeyDecline::ContractionPresenceMismatch => ("ContractionPresenceMismatch", None),
        KeyDecline::ReduceNotGatedToRed => ("ReduceNotGatedToRed", None),
        KeyDecline::BadAccMpField => ("BadAccMpField", None),
        KeyDecline::RedundantAccMpField => ("RedundantAccMpField", None),
        KeyDecline::NonCanonicalReduceField => ("NonCanonicalReduceField", None),
    }
}

/// The wire KIND of every `KeyDecline` variant, for the injectivity guard. Exhaustiveness
/// (the `decline_wire` match above, E0004-guarded) proves every variant maps to SOMETHING;
/// it does NOT prove two variants don't map to the SAME string — an injective failure is
/// silent (green build, two declines collapsed in the artifact). The vectors test asserts
/// these are pairwise distinct against a pinned count.
///
/// This vec is a hand-listed representative per variant. KEEP IN LOCKSTEP with
/// `decline_wire`: a new `KeyDecline` variant is an E0004 there, and the pinned count in
/// the injectivity test is the deliberate second gate so this list cannot silently fall
/// behind (KISS-Conform: asserted counts are pinned, not computed).
pub fn all_decline_wire_kinds() -> Vec<&'static str> {
    [
        KeyDecline::WrongFieldCount { got: 0 },
        KeyDecline::BadVersionPrefix,
        KeyDecline::UnsupportedSchemaVersion { got: 0 },
        KeyDecline::BadRank,
        KeyDecline::BadWorkClass,
        KeyDecline::BadOperandSubKey,
        KeyDecline::BadReduceField,
        KeyDecline::BadContractionField,
        KeyDecline::UppercaseOrWidthHex,
        KeyDecline::UnknownOpFamily,
        KeyDecline::UnknownDtype,
        KeyDecline::ReservedDtype,
        KeyDecline::TokenLengthOutOfBound { len: 0 },
        KeyDecline::TooManyOperands { got: 0 },
        KeyDecline::BadTargetGrammar,
        KeyDecline::BadTargetCharset,
        KeyDecline::ContractionPresenceMismatch,
        KeyDecline::ReduceNotGatedToRed,
        KeyDecline::BadAccMpField,
        KeyDecline::RedundantAccMpField,
        KeyDecline::NonCanonicalReduceField,
    ]
    .iter()
    .map(|e| decline_wire(e).0)
    .collect()
}

/// Emit the reference-vectors artifact as pretty JSON (2-space indent, trailing
/// newline) — the exact bytes committed to `conformance/corpus/structure_key_vectors.json`.
/// The vectors test asserts this output equals the committed file byte-for-byte
/// (`emit() == committed`), so a stale artifact fails CI.
///
/// Every token is produced HERE by the codec: positives via [`StructureKey::to_token`],
/// declines via [`from_token`]. A "decline" input that unexpectedly parses is a
/// generation-time panic, not a silently-wrong artifact.
pub fn emit_reference_vectors_json() -> String {
    let usable: Vec<&str> = DTYPES.iter().copied().filter(|d| !RESERVED_DTYPES.contains(d)).collect();

    let mut s = String::new();
    s.push_str("{\n");
    s.push_str(&format!("  \"schema\": {},\n", json_str(VECTORS_SCHEMA)));
    s.push_str("  \"generated_from\": \"spec/classify.md\",\n");
    s.push_str(&format!("  \"source_commit\": {},\n", json_str(SOURCE_COMMIT)));
    s.push_str("  \"clause\": \"KISS-CLASSIFY-6.7\",\n");
    // Per-namespace vocabulary provenance (#200). Emitted for exactly the
    // namespaces the vectors actually embed, DERIVED from the vectors rather than
    // listed by hand — a hand-listed set can omit a namespace some vector uses,
    // which is the omission this block exists to make impossible.
    {
        let pv = positive_vectors();
        // GENERATION-TIME VALIDATION (#200 req 3): every embedded target must be
        // well-formed under its owning document's grammar, not merely stamped with a
        // version. A stamp catches a bump; it does not catch a token malformed when
        // written — and no consumer can catch that either, because they copy it.
        for v in &pv {
            validate_target_token(&v.key.target);
        }
        let mut seen: Vec<&str> = pv
            .iter()
            .map(|v| target_namespace(&v.key.target))
            .collect();
        seen.sort_unstable();
        seen.dedup();
        s.push_str("  \"namespace_vocabulary_note\": \"Each <namespace>: token is spelled in a vocabulary owned by that namespace's maintainer (KISS-CLASSIFY-6.8-0004), versioned independently of this artifact. These are the versions the tokens below were GENERATED AGAINST; a consumer asserting a vocabulary version (KISS-CLASSIFY-6.8-0009) asserts against these. The generator FAILS rather than emit a token whose vocabulary version it cannot state.\",\n");
        s.push_str("  \"namespace_vocabulary_versions\": {\n");
        for (i, ns) in seen.iter().enumerate() {
            let comma = if i + 1 < seen.len() { "," } else { "" };
            s.push_str(&format!("    {}: {}{}\n", json_str(ns), namespace_vocab_version(ns), comma));
        }
        s.push_str("  },\n");
    }
    s.push_str(&format!("  \"structure_key_schema_version\": {},\n", SCHEMA_VERSION));
    s.push_str("  \"token_prefix\": \"sk4\",\n");
    s.push_str("  \"dtype_axis_note\": \"recognition_set is all 24 tokens a reader MUST recognize on parse (reserved ones typed-decline, distinct from unknown); usable_set is the 22 a byte-match runs over. The two are different obligations (KISS-CLASSIFY-6.1-0001).\",\n");
    s.push_str(&format!("  \"recognition_count\": {},\n", DTYPES.len()));
    s.push_str(&format!("  \"usable_count\": {},\n", usable.len()));

    // dtype sets, in §6.1-table order (ordinal-significant per §6.19-0025).
    s.push_str("  \"dtype_recognition_set\": [\n");
    for (i, d) in DTYPES.iter().enumerate() {
        let comma = if i + 1 < DTYPES.len() { "," } else { "" };
        s.push_str(&format!("    {}{}\n", json_str(d), comma));
    }
    s.push_str("  ],\n");
    s.push_str("  \"dtype_usable_set\": [\n");
    for (i, d) in usable.iter().enumerate() {
        let comma = if i + 1 < usable.len() { "," } else { "" };
        s.push_str(&format!("    {}{}\n", json_str(d), comma));
    }
    s.push_str("  ],\n");
    s.push_str("  \"reserved_dtypes\": [\n");
    for (i, d) in RESERVED_DTYPES.iter().enumerate() {
        let comma = if i + 1 < RESERVED_DTYPES.len() { "," } else { "" };
        s.push_str(&format!("    {}{}\n", json_str(d), comma));
    }
    s.push_str("  ],\n");

    // target-namespace axis — the same machine-readable treatment the dtype axis got.
    // There is NO typed namespace enum at this schema version (StructureKey.target is the
    // §6.8-0001 free-form <namespace>:<capability-set> string), so `target_namespace` is
    // derived from `target`; the vectors test cross-checks it against the SERIALIZED token
    // with its own independent split, never against the same derivation, so the tag cannot
    // pass vacuously.
    let pos = positive_vectors();
    let mut namespaces: Vec<&str> = pos.iter().map(|v| target_namespace(&v.key.target)).collect();
    namespaces.sort_unstable();
    namespaces.dedup();
    s.push_str("  \"target_axis_note\": \"Each positive vector names the `target` capability token it requires and its `target_namespace`. A consumer implementing only some namespaces/architectures scopes the rest as capability EXCLUSIONS (conformant, KISS-CLASSIFY-6.8), never mismatches — on BOTH sub-axes: namespace (cuda vs vulkan) and capability/arch (sm89 vs sm90). With these tags a consumer reports N/N on the vectors it claims plus an explicit skip list, instead of N-1/N with a paragraph — the number stops depending on prose.\",\n");
    s.push_str("  \"target_namespaces\": [\n");
    for (i, ns) in namespaces.iter().enumerate() {
        let comma = if i + 1 < namespaces.len() { "," } else { "" };
        s.push_str(&format!("    {}{}\n", json_str(ns), comma));
    }
    s.push_str("  ],\n");
    s.push_str("  \"mapping_guard_note\": \"The `decline` kind strings are KISS's vocabulary. KISS enforces their exhaustiveness at generation time (a new KeyDecline variant is a build error) — that protects only the KISS side. A consumer mapping these onto its own decline enum MUST guard the mapping itself; a variant added on either side silently staleness the table.\",\n");
    s.push_str("  \"coverage_note\": \"The positive vectors exercise the structure_key token GRAMMAR — field order, optional-field presence, sentinel spellings, work-class/dispatch, and decline verdicts — NOT the dtype vocabulary: they place only a few of the 22 usable dtypes in the dtype position, so a dtype-spelling divergence on a token that never appears is invisible to a byte-match against this set. Vocabulary agreement is a DIFFERENT instrument's job and IS closed there: the dtype-manifest gate — tools/test_kiss_dtypes_manifest.py, over conformance/corpus/dtype_manifest.json — asserts each dtype token's metadata, so a c128->c127 respell raises there, naming the token. Nor do the POSITIVE vectors test decline-side rules: rule (d) — rejecting the all-default redundant (acc+mp) form — is exercised only by the decline vector 'redundant_acc_mp_all_default' -> RedundantAccMpField (a deriver covers it by running the DECLINE vectors on the parse side, or by proving the redundant form unconstructible on the emit side; never by the positive byte-match). So 'the byte-match passed' means the token grammar agrees; the vocabulary is confirmed by the manifest and the decline-side rules by the decline vectors, not by this positive set.\",\n");

    // positive vectors: token emitted by the codec (to_token).
    s.push_str("  \"positive_vectors\": [\n");
    for (i, v) in pos.iter().enumerate() {
        let comma = if i + 1 < pos.len() { "," } else { "" };
        s.push_str("    {\n");
        s.push_str(&format!("      \"clause\": {},\n", json_str(v.clause)));
        s.push_str(&format!("      \"name\": {},\n", json_str(v.name)));
        s.push_str(&format!("      \"note\": {},\n", json_str(v.note)));
        s.push_str(&format!("      \"target\": {},\n", json_str(&v.key.target)));
        s.push_str(&format!("      \"target_namespace\": {},\n", json_str(target_namespace(&v.key.target))));
        s.push_str(&format!("      \"token\": {}\n", json_str(&v.key.to_token())));
        s.push_str(&format!("    }}{}\n", comma));
    }
    s.push_str("  ],\n");

    // decline vectors: decline emitted by the codec (from_token, live).
    let dec = decline_vectors();
    s.push_str("  \"decline_vectors\": [\n");
    for (i, d) in dec.iter().enumerate() {
        let comma = if i + 1 < dec.len() { "," } else { "" };
        // the decline is codec-emitted (from_token, live) but PUBLISHED through the
        // stable wildcard-free mapping, never through Debug.
        let e = match from_token(&d.token) {
            Err(e) => e,
            Ok(_) => panic!(
                "decline vector `{}` unexpectedly parsed as a valid token: {}",
                d.name, d.token
            ),
        };
        let (kind, payload) = decline_wire(&e);
        s.push_str("    {\n");
        s.push_str(&format!("      \"clause\": {},\n", json_str(d.clause)));
        s.push_str(&format!("      \"name\": {},\n", json_str(d.name)));
        s.push_str(&format!("      \"note\": {},\n", json_str(d.note)));
        s.push_str(&format!("      \"token\": {},\n", json_str(&d.token)));
        match payload {
            // structured payload: a JSON number, not Rust struct syntax in a string.
            Some((k, v)) => {
                s.push_str(&format!("      \"decline\": {},\n", json_str(kind)));
                s.push_str(&format!("      {}: {}\n", json_str(k), v));
            }
            None => s.push_str(&format!("      \"decline\": {}\n", json_str(kind))),
        }
        s.push_str(&format!("    }}{}\n", comma));
    }
    s.push_str("  ]\n");
    s.push_str("}\n");
    s
}
